### ISSUE TITLE
La concaténation des valeurs du calvier virtuel

### ISSUE THREAD

**Issue by osaaoui** [osaaoui/grapher#1]
Salut,
petite progression dans l'affichage des valeurs du clavier virtuel. Seulement, les deux valeurs (input + clavier virtuel) sont séparés par des espaces. par exemple: 2             x2    
Alors c'est un truc supplémentaire à règler même si pour le moment on se sert pas vraiment du clavier virtuel pour entrer des données.
omar

**Comment by marcanto797** [comment]
Je tout change' le script clavier. Maintenant il affiches les bon choses mais par contre il n y a pas d'effet réel sur le graph
