### ISSUE TITLE
bulles qui se superposent

### ISSUE THREAD

**Issue by osaaoui** [osaaoui/grapher#6]
les bulles ordonnée à l'intérieur du graphe se superposent. Si on bouge la courbe, l’ancienne bulle reste et la nouvelle se superpose à l’ancienne.

**Comment by marcanto797** [comment]
Bug fixe. Maintenant le point et sa bulle sont efface quand on utilise le button ordonnee a nouveau ou si on "hover" sur le graph. 
La bulle reste dynamique.
